
[defaults]
project_name = "testproject"
project_repository = "UBC-DERC"
git_platform = "github.com"
project_description = "A copier placeholder to make sure things work."
author_formal = "LastName IV"
author_given = "Smongus"
author_orcid = "https://orcid.org/0000-0002-2700-4605"
license_type = "Mozilla Public License 2.0"
code_of_conduct_lang = "code_fr"

[output.".ctt/copier_include"]
version = "1.2.3"
