
[defaults]
project_title = "This Big Title Name"
project_repository = "UBC-DERC"
git_platform = "github.com"
project_description = "A copier placeholder to make sure things work."
author_formal = "LastName IV"
author_given = "Smongus"
author_orcid = "https://orcid.org/0000-0002-2700-4605"
author_email = "banana@banana.banana"
license_type = "MPL-2.0"
code_of_conduct_lang = "code_fr"
primary_language = "r"

[output.".ctt/copier_include"]
version = "1.2.3"

[output.".ctt/mpl"]
license_type = "MPL-2.0"

[output.".ctt/apache"]
license_type = "Apache-2.0"

[output.".ctt/mit"]
license_type = "MIT"

[output.".ctt/no-license"]
license_type = "No License"

[output.".ctt/r-proj"]
project_title = "My Project"
primary_language = "r"

[output.".ctt/python-proj"]
primary_language = "python"
project_title = "My Project"

[output.".ctt/awardlists"]
nserc_award = "RGPIN-2023-04350,RGPIN-2023-04350, RGPIN-2021-04350"
cihr_award = "123450"
sshrc_award = "410-2004-1234"