site_name: DERC GitHub Best Practices

theme:
  name: material
  features:
    - navigation.indexes
    - navigation.sections
    - navigation.top
    - navigation.tracking
    - toc.follow
    - content.code.copy
  palette:
    - scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

nav:
  - Home: index.md
  - Template Features: features.md
  - Using the DERC Template:
      - copier/using/index.md
      - Installing the Tools: copier/using/installing.md
      - Building Your Project: copier/using/building.md
      - Keeping in Sync: copier/using/updating.md
  - Best Practices:
      - copier/index.md
      - Building Better Code: copier/building/index.md
      - It's Your Work — Attribution: copier/attribution/index.md
      - Building Community: copier/community/index.md
      - Staying Organized: copier/organization/index.md
