name: Bug Report
description: File a bug report.
title: "[Bug]: "
labels: ["bug", "triage"]
assignees:
  - SimonGoring
type: bug
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out a bug report for the DERC Copier!
  - type: input
    id: contact
    attributes:
      label: Contact Details
      description: How can we get in touch with you if we need more info?
      placeholder: ex. email@example.com
    validations:
      required: false
  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: Also tell us, what did you expect to happen?
      placeholder: Tell us what you see!
      value: "A bug happened!"
    validations:
      required: true
  - type: dropdown
    id: version
    attributes:
      label: Version
      description: What version of our software are you running?
      options:
        - 26.09 (Most recent version)
        - 26.08.x
      default: 0
    validations:
      required: true
  - type: dropdown
    id: language
    attributes:
      label: What programming language are you using?
      multiple: true
      options:
        - Python
        - R
        - Other
  - type: textarea
    id: answers
    attributes:
      label: Relevant answers.yml file
      description: Please copy and paste your answers.yml file (if produced). Otherwise, copy the error message you received.
      render: shell
  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: By submitting this issue, you agree to follow our [Code of Conduct](https://github.com/UBC-DERC/derc_copier/blob/main/CODE_OF_CONDUCT.md).
      options:
        - label: I agree to follow this project's Code of Conduct
          required: true
  - type: upload
    id: screenshots
    attributes:
      label: Upload screenshots
      description: If applicable, add screenshots to help explain your problem.
    validations:
      required: false
