name: core_actions
on:
    push:
        branches:
            - main
    pull_request:
        branches:
            - main
permissions: {}
jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: checkout
              uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
            - name: Install uv
              uses: astral-sh/setup-uv@08807647e7069bb48b6ef5acd8ec9567f424441b # v8.1.0
              with:
                enable-cache: true
            - name: Set up git for later use.
              run: |                                                                                                          
                git config --global user.email "ci@ubc-derc.example"                                                          
                git config --global user.name "DERC CI"
            - run: uv sync
            - name: Lint (ruff)
              run: uv run ruff check .
            - name: Test coper build
              run: uv run ctt
            - name: Test package load
              run: uv run pytest .ctt/copier_include/tests/test_exists.py
            - name: Test package load with coverage
              run: uv run pytest --cov=. --cov-report=xml .ctt/copier_include/tests/test_exists.py
            - name: Check whether the citation metadata from CITATION.cff is valid
              uses: citation-file-format/cffconvert-github-action@af1004e6eb5ebfadad8450ebcdceefb3866190e1
              with:
                args: "--validate --infile .ctt/copier_include/CITATION.cff"